In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Product': ['Laptop', 'Smartphone', 'Headphones', 'Smartwatch'],
    'Category': ['Electronics', 'Electronics', 'Audio', 'Wearables'],
    'Price': [899.99, 599.50, 149.99, 199.00],
    'Stock': [15, 30, 120, 45]
}
df = pd.DataFrame(data)
df

      Product     Category   Price  Stock
0      Laptop  Electronics  899.99     15
1  Smartphone  Electronics  599.50     30
2  Headphones        Audio  149.99    120
3  Smartwatch    Wearables  199.00     45

In [4]:
employee_data = [
    ['TechGadget X', 'Electronics', 149.99, 45],
    ['EcoBottle 1L', 'Kitchenware', 24.50, 120],
    ['FitTrack Pro', 'Fitness', 89.00, 75],
    ['SmartBulb RGB', 'Home Automation', 19.99, 210]
]
columns = ["Product_Name", "Category", "Price", "Stock_Level"]
df2 = pd.DataFrame(employee_data , columns=columns)
df2

    Product_Name         Category   Price  Stock_Level
0   TechGadget X      Electronics  149.99           45
1   EcoBottle 1L      Kitchenware   24.50          120
2   FitTrack Pro          Fitness   89.00           75
3  SmartBulb RGB  Home Automation   19.99          210

Slicing

In [5]:
df2[["Category" , "Price"]]

          Category   Price
0      Electronics  149.99
1      Kitchenware   24.50
2          Fitness   89.00
3  Home Automation   19.99

Creating a New column

In [6]:
df2["Star"] = [ 4 , 5, 2, 1]
df2

    Product_Name         Category   Price  Stock_Level  Star
0   TechGadget X      Electronics  149.99           45     4
1   EcoBottle 1L      Kitchenware   24.50          120     5
2   FitTrack Pro          Fitness   89.00           75     2
3  SmartBulb RGB  Home Automation   19.99          210     1

Removing columns

In [7]:
df2.drop(0, axis= 0)

    Product_Name         Category  Price  Stock_Level  Star
1   EcoBottle 1L      Kitchenware  24.50          120     5
2   FitTrack Pro          Fitness  89.00           75     2
3  SmartBulb RGB  Home Automation  19.99          210     1

In [8]:
df2

    Product_Name         Category   Price  Stock_Level  Star
0   TechGadget X      Electronics  149.99           45     4
1   EcoBottle 1L      Kitchenware   24.50          120     5
2   FitTrack Pro          Fitness   89.00           75     2
3  SmartBulb RGB  Home Automation   19.99          210     1

In [9]:
df2.loc[[0 ,1]]

   Product_Name     Category   Price  Stock_Level  Star
0  TechGadget X  Electronics  149.99           45     4
1  EcoBottle 1L  Kitchenware   24.50          120     5

In [10]:
df2.iloc[3]

Product_Name      SmartBulb RGB
Category        Home Automation
Price                     19.99
Stock_Level                 210
Star                          1
Name: 3, dtype: object

Selecting subsets Rows & Columns

In [11]:
df

      Product     Category   Price  Stock
0      Laptop  Electronics  899.99     15
1  Smartphone  Electronics  599.50     30
2  Headphones        Audio  149.99    120
3  Smartwatch    Wearables  199.00     45

In [12]:
df.loc[[0 , 1]][["Product", "Price"]]

      Product   Price
0      Laptop  899.99
1  Smartphone  599.50

Applying Conditions

In [15]:
df2

    Product_Name         Category   Price  Stock_Level  Star
0   TechGadget X      Electronics  149.99           45     4
1   EcoBottle 1L      Kitchenware   24.50          120     5
2   FitTrack Pro          Fitness   89.00           75     2
3  SmartBulb RGB  Home Automation   19.99          210     1

In [ ]:
df2[df2["Stock_Level"] > 100]

    Product_Name         Category  Price  Stock_Level  Star
1   EcoBottle 1L      Kitchenware  24.50          120     5
3  SmartBulb RGB  Home Automation  19.99          210     1

Applying multiple Conditions

In [26]:
df2[(df2["Stock_Level"] >30) & (df2["Star"] > 3)]

   Product_Name     Category   Price  Stock_Level  Star
0  TechGadget X  Electronics  149.99           45     4
1  EcoBottle 1L  Kitchenware   24.50          120     5