In [5]:
import numpy as pd
import pandas as pd

In [8]:
students = pd.DataFrame({
    'student_id':[1 , 2 ,3, 4 , 5],
    'name': ['Alice', 'Liam', 'Sophia', 'Mason', 'Emma'],
    'major': ['Computer Science', 'Mathematics', 'Physics', 'Computer Science', 'Chemistry']
})

grades = pd.DataFrame({
    'student_id':[1 , 2 ,3, 6 , 7],
    'credits_earned':[4 , 3 ,2, 4 , 2],
    'gpa': [3.8, 3.5, 3.9, 2.8, 3.7]
})

In [9]:
students

   student_id    name             major
0           1   Alice  Computer Science
1           2    Liam       Mathematics
2           3  Sophia           Physics
3           4   Mason  Computer Science
4           5    Emma         Chemistry

In [10]:
grades

   student_id  credits_earned  gpa
0           1               4  3.8
1           2               3  3.5
2           3               2  3.9
3           6               4  2.8
4           7               2  3.7

In [ ]:
# how='inner': Specifies the type of merge. An inner join returns only the intersecting values (matches) found in both tables    

pd.merge(students,grades, on='student_id', how ='inner')

   student_id    name             major  credits_earned  gpa
0           1   Alice  Computer Science               4  3.8
1           2    Liam       Mathematics               3  3.5
2           3  Sophia           Physics               2  3.9

In [ ]:
# how='outer': Specifies that all rows from both tables must be included

pd.merge(students,grades, on='student_id', how ='outer')

   student_id    name             major  credits_earned  gpa
0           1   Alice  Computer Science             4.0  3.8
1           2    Liam       Mathematics             3.0  3.5
2           3  Sophia           Physics             2.0  3.9
3           4   Mason  Computer Science             NaN  NaN
4           5    Emma         Chemistry             NaN  NaN
5           6     NaN               NaN             4.0  2.8
6           7     NaN               NaN             2.0  3.7

In [ ]:
# how='left': Specifies that the merge must prioritize the left table.

pd.merge(students,grades, on='student_id', how ='left')

   student_id    name             major  credits_earned  gpa
0           1   Alice  Computer Science             4.0  3.8
1           2    Liam       Mathematics             3.0  3.5
2           3  Sophia           Physics             2.0  3.9
3           4   Mason  Computer Science             NaN  NaN
4           5    Emma         Chemistry             NaN  NaN

In [ ]:
# how='left': Specifies that the merge must prioritize the right table.

pd.merge(students,grades, on='student_id', how ='right')

   student_id    name             major  credits_earned  gpa
0           1   Alice  Computer Science               4  3.8
1           2    Liam       Mathematics               3  3.5
2           3  Sophia           Physics               2  3.9
3           6     NaN               NaN               4  2.8
4           7     NaN               NaN               2  3.7

Concatination of 2 Dataframes
{stacking multiple DataFrame objects together either vertically (row-wise) or horizontally (column-wise)}

In [17]:
df1 = pd.DataFrame({
'A': ['AO', 'A1', 'A2'],
'B':['B0', 'B1', 'B2'],
'C':['co', 'c1', 'C2']

})

df2 = pd.DataFrame({
'A': ['A3', 'A4', 'A5'],
'B': ['B3', 'B4', 'B5'],
'C': ['C3', 'C4', 'C5']
})

In [18]:
df1

    A   B   C
0  AO  B0  co
1  A1  B1  c1
2  A2  B2  C2

In [19]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [20]:
pd.concat([df2 , df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  AO  B0  co
1  A1  B1  c1
2  A2  B2  C2

In [22]:
# axis 1 refers to columns, else it is auto set to axis 0 which refers to rows

pd.concat([df2 , df1], axis = 1)

    A   B   C   A   B   C
0  A3  B3  C3  AO  B0  co
1  A4  B4  C4  A1  B1  c1
2  A5  B5  C5  A2  B2  C2

Joining Two DataFrames

In [23]:
df1 = pd.DataFrame({
'name': ['Ace', 'Luffy', 'Sabo']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
'score': [85, 90, 75]
}, index=[2, 3, 4])

In [27]:
df1

    name
1    Ace
2  Luffy
3   Sabo

In [28]:
df2

   score
2     85
3     90
4     75

In [29]:
df1.join(df2,how='outer')

    name  score
1    Ace    NaN
2  Luffy   85.0
3   Sabo   90.0
4    NaN   75.0

In [30]:
df2.join(df1)

   score   name
2     85  Luffy
3     90   Sabo
4     75    NaN